# Generated by Django 4.1 on 2022-08-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress',
            new_name='address',
        ),
    ]
