# Generated by Django 3.1.4 on 2022-08-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Homee',
        ),
    ]
