# Generated by Django 3.1.4 on 2022-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20220829_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homee',
            name='description',
        ),
        migrations.AlterField(
            model_name='homee',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
