# Generated by Django 3.1.4 on 2022-08-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teamm',
        ),
    ]
