# Generated by Django 3.1.4 on 2022-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20220829_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homee',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
